sgtitle('Aerodynamic inputs', 'Interpreter', 'Latex', 'fontsize', 16)
subplot(3,1,1)
plot(out.alpha_coeff, 'linewidth', 3)
title('$\alpha$', 'Interpreter', 'Latex', 'fontsize', 16)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('$\alpha$ [deg]', 'Interpreter', 'Latex', 'fontsize', 16)
xlim([0,time*1.2])
set(gca, 'fontsize', 16)

subplot(3,1,2)
plot(out.beta_coeff, 'linewidth', 3)
title('$\beta$', 'Interpreter', 'Latex', 'fontsize', 16)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('$\beta$ [deg]', 'Interpreter', 'Latex', 'fontsize', 16)
xlim([0,time*1.2])
set(gca, 'fontsize', 16)

subplot(3,1,3)
plot(out.dyn_pres, 'linewidth', 3)
title('Dynamic Pressure', 'Interpreter', 'Latex', 'fontsize', 16)
xlim([0,time*1.2])
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('q [Pa]', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)