sgtitle('Aerodynamic disturbances', 'Interpreter', 'Latex', 'fontsize', 16)
subplot(2,1,1)
plot(out.Faero, 'linewidth', 3)
xlabel('Time [s]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('Disturbing Force [N]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Aerodynamic Forces', 'Interpreter', 'Latex', 'fontsize', 16)
xlim([0,18])
legend('x', 'y', 'z')
set(gca, 'fontsize', 16)

subplot(2,1,2)
plot(out.Maero, 'linewidth', 3)
xlabel('Time [s]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('Disturbing Moment [Nm]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Aerodynamic Moments', 'Interpreter', 'Latex', 'fontsize', 16)
xlim([0,18])
legend('x', 'y', 'z')
set(gca, 'fontsize', 16)