subplot(2,3,1)
plot3(XI_Cx, YI_Cx, ZI_Cx)
title('C_X')
xlabel('alpha')
ylabel('beta')
zlabel('Coeff')

subplot(2,3,2)
plot3(XI_Cy, YI_Cy, ZI_Cy)
title('C_Y')
xlabel('alpha')
ylabel('beta')
zlabel('Coeff')

subplot(2,3,3)
plot3(XI_Cz, YI_Cz, ZI_Cz)
title('C_Z')
xlabel('alpha')
ylabel('beta')
zlabel('Coeff')

subplot(2,3,4)
plot3(XI_p, YI_p, ZI_p)
title('C_m,p')
xlabel('alpha')
ylabel('beta')
zlabel('Coeff')

subplot(2,3,5)
plot3(XI_q, YI_q, ZI_q)
title('C_m,q')
xlabel('alpha')
ylabel('beta')
zlabel('Coeff')

subplot(2,3,6)
plot3(XI_r, YI_r, ZI_r)
title('C_m,r')
xlabel('alpha')
ylabel('beta')
zlabel('Coeff')