sgtitle('Gust Control only angular, transformation and aerodynamic model, at 100 km/hr', 'Interpreter', 'Latex', 'fontsize', 16)
subplot(4,1,1)
plot(out.theta_gust, 'linewidth', 3)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('$\theta$ [m]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Angle deviation', 'Interpreter', 'Latex', 'fontsize', 16)
legend('x', 'y', 'z', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)

subplot(4,1,2)
plot(out.Maero_gust, 'linewidth', 3)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('$M_{aero}$ [N]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Aerodynamic moment', 'Interpreter', 'Latex', 'fontsize', 16)
legend('x', 'y', 'z', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)
xlim([0,25])

subplot(4,1,3)
plot(out.alpha_gust, 'linewidth', 3)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('$\alpha_{y}$ [N]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Angular acceleration', 'Interpreter', 'Latex', 'fontsize', 16)
legend('x', 'y', 'z', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)
xlim([0.25,25])

subplot(4,1,4)
plot(out.M_gust, 'linewidth', 3)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('$F_{y}$ [N]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Control Force', 'Interpreter', 'Latex', 'fontsize', 16)
legend('x', 'y', 'z', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)
xlim([0,25])