sgtitle('Linear Dynamics', 'Interpreter', 'Latex', 'fontsize', 16)

subplot(3,1,1)
plot(out.r, 'linewidth', 3)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('Position [m]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Position', 'Interpreter', 'Latex', 'fontsize', 16)
legend('x', 'y', 'z', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)

subplot(3,1,2)
plot(out.v, 'linewidth', 3)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('Velocity [m/s]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Velocity', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)

subplot(3,1,3)
plot(out.a, 'linewidth', 3)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('Acceleration [$m/s^2$]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Acceleration', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)