sgtitle('Angular Dynamics Results', 'Interpreter', 'Latex', 'fontsize', 16)
subplot(2,1,1)
plot(out.alpha, 'linewidth', 2)
%yline(0.325, 'linewidth', 1.5)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('$\alpha$ [$rad/s^2$]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Magnitude of angular acceleration', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)
xlim([0.1,35])
%legend('$a$', '$a_{lim}$', 'Interpreter', 'Latex', 'fontsize', 16)

subplot(2,1,2)
plot(out.theta_tot, 'linewidth', 2)
%yline(1, 'linewidth', 1.5)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('$\theta$ [deg]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Magnitude of angle deviation', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)
%legend('$a$', '$a_{lim}$', 'Interpreter', 'Latex', 'fontsize', 16)
%ylim([0, 1.25])