sgtitle('Gust Control only linear and aerodynamic model, at 100 km/hr', 'Interpreter', 'Latex', 'fontsize', 16)
subplot(4,1,1)
plot(out.rygust, 'linewidth', 3)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('$r_y$ [m]', 'Interpreter', 'Latex', 'fontsize', 16)
title('y-deviation', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)
xlim([0,25])

subplot(4,1,2)
plot(out.Gust, 'linewidth', 3)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('$F_{aero_y}$ [N]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Aerodynamic force', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)
xlim([0,25])

subplot(4,1,3)
plot(out.aygust, 'linewidth', 3)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('$a_{y}$ [N]', 'Interpreter', 'Latex', 'fontsize', 16)
title('y-Acceleration', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)
xlim([0,25])

subplot(4,1,4)
plot(out.Fygust, 'linewidth', 3)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('$F_{y}$ [N]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Control Force', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)
xlim([0,25])