sgtitle('Control Propeller Thrusts', 'Interpreter', 'Latex', 'fontsize', 16)
subplot(3,1,1)
plot(out.Fc1, 'linewidth', 3)
title('Back-Top', 'Interpreter', 'Latex', 'fontsize', 16)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('Thrust [N]', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)

subplot(3,1,2)
plot(out.Fc2, 'linewidth', 3)
title('Back-Bottom', 'Interpreter', 'Latex', 'fontsize', 16)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('Thrust [N]', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)

subplot(3,1,3)
plot(out.Fc3, 'linewidth', 3)
title('Front-Bottom', 'Interpreter', 'Latex', 'fontsize', 16)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('Thrust [N]', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)