plot(out.gyro, 'linewidth', 3)
title('Gyroscope Model', 'Interpreter', 'Latex', 'fontsize', 16)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('Gyroscope Error [$rad/s^2$]', 'Interpreter', 'Latex', 'fontsize', 16)
legend('x', 'y', 'z', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)