subplot(3,1,1)
plot(out.alpha_coeff)
title('Alpha')
xlabel('Time [sec]')
ylabel('alpha [deg]')
xlim([0,time*1.2])
%set(gca,'YTick',-2*pi:pi/2:2*pi) 
%set(gca,'YTickLabel',{'-pi/2', '-pi/4', '0','pi/4', 'pi/2'})

subplot(3,1,2)
plot(out.beta_coeff)
title('Beta')
xlabel('Time [sec]')
ylabel('beta [deg]')
xlim([0,time*1.2])
%set(gca,'YTick',-2*pi:pi/2:2*pi) 
%set(gca,'YTickLabel',{'-pi/2', '-pi/4', '0', 'pi/2'})

subplot(3,1,3)
plot(out.dyn_pres)
title('Dynamic Pressure')
xlim([0,time*1.2])
xlabel('Time [sec]')
ylabel('Dynamic pressure [Pa]')