sgtitle('Top \& Bottom Propeller Thrusts', 'Interpreter', 'Latex', 'fontsize', 16)
subplot(3,1,1)
plot(out.Ft1, 'linewidth', 3)
title('Top-front propellers', 'Interpreter', 'Latex', 'fontsize', 16)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('Thrust [N]', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)

subplot(3,1,2)
plot(out.Ft3, 'linewidth', 3)
title('Back propellers', 'Interpreter', 'Latex', 'fontsize', 16)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('Thrust [N]', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)

subplot(3,1,3)
plot(out.Fb1, 'linewidth', 3)
title('Front-bottom propellers', 'Interpreter', 'Latex', 'fontsize', 16)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('Thrust [N]', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)
