sgtitle('Linear Dynamics Results', 'Interpreter', 'Latex', 'fontsize', 16)
subplot(2,1,1)
plot(out.acc, 'linewidth', 2)
yline(0.325, 'linewidth', 1.5)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('a [$m/s^2$]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Magnitude of Acceleration', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)
legend('$a$', '$a_{lim}$', 'Interpreter', 'Latex', 'fontsize', 16)

subplot(2,1,2)
plot(out.rtot, 'linewidth', 2)
yline(1, 'linewidth', 1.5)
xlabel('Time [sec]', 'Interpreter', 'Latex', 'fontsize', 16)
ylabel('r [m]', 'Interpreter', 'Latex', 'fontsize', 16)
title('Magnitude of position deviation', 'Interpreter', 'Latex', 'fontsize', 16)
set(gca, 'fontsize', 16)
legend('$a$', '$a_{lim}$', 'Interpreter', 'Latex', 'fontsize', 16)
ylim([0, 1.25])